require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'app/validators/**/*'
    - 'db/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
  Exclude:
    - 'spec/factories/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  # para não apontar falta de comentários antes das classes
  Enabled: false  

Style/FrozenStringLiteralComment:
  Enabled: false  
